name: dio_cache_interceptor_hive_store_example
description: dio_cache_interceptor_hive_store example.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio:
  dio_cache_interceptor:
  dio_cache_interceptor_hive_store:
  path_provider:

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^2.0.1
