name: dio_cache_interceptor
description: Dio HTTP cache interceptor with multiple stores respecting HTTP directives (ETag, Last-Modified, Cache-Control) with options.
repository: https://github.com/llfbandit/dio_cache_interceptor
issue_tracker: https://github.com/llfbandit/dio_cache_interceptor/issues

version: 0.6.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  sqflite: ^1.3.2+1
  uuid: ^2.2.2
  meta: ^1.2.4
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  # Tests are done in example project
