name: dio_cache_interceptor_isar_store
description: A DB cache store implementation with Isar for dio_cache_interceptor package.
version: 1.0.1
repository: https://github.com/llfbandit/dio_cache_interceptor
issue_tracker: https://github.com/llfbandit/dio_cache_interceptor/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dio_cache_interceptor: ^3.5.0

  # https://pub.dev/packages/isar
  isar: ^3.1.0+1
  # https://pub.dev/packages/isar_flutter_libs
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  isar_generator: ^3.1.0+1
  build_runner: any

  # https://pub.dev/packages/lints
  lints: ^3.0.0
  # https://pub.dev/packages/test
  test: ^1.23.1
