name: dio_cache_interceptor_db_store_example
description: dio_cache_interceptor_db_store example.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  dio:
  dio_cache_interceptor:
  dio_cache_interceptor_db_store:
  path_provider:

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^3.0.0
