name: dio_cache_interceptor_hive_store
description: A DB cache store implementation with Hive for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/dio_cache_interceptor_hive_store
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cache_interceptor: ^3.0.0

  # https://pub.dev/packages/hive
  hive: ^2.0.3

dev_dependencies:
  # https://pub.dev/packages/pedantic
  pedantic: ^1.11.0
  # https://pub.dev/packages/test
  test: ^1.16.8
