name: dio_cache_interceptor_db_store
description: A DB cache store implementation with Moor for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_db_store
version: 4.1.1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cache_interceptor: ^3.2.0

  # https://pub.dev/packages/drift
  drift: ^1.1.0
  # https://pub.dev/packages/path
  path: ^1.8.0

dev_dependencies:
  # https://pub.dev/packages/drift_dev
  drift_dev: ^1.1.1
  # https://pub.dev/packages/build_runner
  build_runner: ^2.0.5
  # https://pub.dev/packages/lints
  lints: ^1.0.1
  # https://pub.dev/packages/sqlite3
  sqlite3: ^1.1.2
  # https://pub.dev/packages/test
  test: ^1.18.0
