name: dio_cache_interceptor_db_store
description: A DB cache store implementation with Drift for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_db_store
version: 5.1.1
environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  dio_cache_interceptor: ^3.3.0

  # https://pub.dev/packages/drift
  drift: ^2.5.0
  # https://pub.dev/packages/path
  path: ^1.8.0

dev_dependencies:
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.5.2
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # https://pub.dev/packages/lints
  lints: ^3.0.0
  # https://pub.dev/packages/test
  test: ^1.23.1

  # Dependencies for downloading SQLite before running tests
  http: ^1.1.0
  archive: ^3.3.1
