name: dio_cache_interceptor_db_store
description: A DB cache store implementation with Drift for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_db_store
version: 5.1.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cache_interceptor: ^3.3.0

  # https://pub.dev/packages/drift
  drift: ^2.5.0
  # https://pub.dev/packages/path
  path: ^1.8.0

# dependency_overrides:
#   dio_cache_interceptor:
#     path: ../dio_cache_interceptor

dev_dependencies:
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.5.2
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # https://pub.dev/packages/lints
  lints: ^2.0.1
  # https://pub.dev/packages/test
  test: ^1.23.1

  # Dependencies for downloading SQLite before running tests
  http: ^0.13.4
  archive: ^3.3.1
