name: dio_cache_interceptor
description: Dio HTTP cache interceptor with multiple stores respecting HTTP directives (or not).
repository: https://github.com/llfbandit/dart_http_cache
issue_tracker: https://github.com/llfbandit/dart_http_cache/issues

version: 4.0.2

environment:
  sdk: ^3.0.0

dependencies:
  # https://pub.dev/packages/dio
  dio: ^5.2.0+1
  http_cache_core: ^1.0.2

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^5.0.0
  # https://pub.dev/packages/test
  test: ^1.24.4
