name: dio_cache_interceptor_objectbox_store
description: A DB cache store implementation with ObjectBox for dio_cache_interceptor package.
version: 1.1.3
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_objectbox_store

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  dio_cache_interceptor: ^3.5.0
  # https://pub.dev/packages/objectbox
  objectbox: ^2.3.1
  # https://pub.dev/packages/flat_buffers
  flat_buffers: ^2.0.5

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # https://pub.dev/packages/objectbox_generator
  objectbox_generator: any
  # https://pub.dev/packages/lints
  lints: ^3.0.0
  # https://pub.dev/packages/test
  test: ^1.23.1
